# Generated by Django 5.2.5 on 2025-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateproduct',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line'),
        ),
    ]
